# Generated by Django 5.2.8 on 2026-04-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Integrated"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="Opsin, Heterologous, or SCP", max_length=50
                    ),
                ),
                ("genus", models.CharField(blank=True, max_length=100, null=True)),
                ("species", models.CharField(blank=True, max_length=100, null=True)),
                ("lambda_max", models.FloatField(blank=True, null=True)),
                ("mutations", models.CharField(blank=True, max_length=255, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("refid", models.AutoField(primary_key=True, serialize=False)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("year_of_publication", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Opsin",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opsinid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gene_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phylum", models.CharField(blank=True, max_length=100, null=True)),
                ("genus", models.CharField(blank=True, max_length=100, null=True)),
                ("species", models.CharField(blank=True, max_length=100, null=True)),
                ("accession", models.CharField(blank=True, max_length=100, null=True)),
                ("dna_sequence", models.TextField(blank=True, null=True)),
                ("protein_sequence", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opsins",
                        to="core.reference",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CuratedSCP",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scpid", models.AutoField(primary_key=True, serialize=False)),
                ("genus", models.CharField(blank=True, max_length=100, null=True)),
                ("species", models.CharField(blank=True, max_length=100, null=True)),
                ("phylum", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "photoreceptor_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Rod, Cone, LWS, SWS",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cell_subtype",
                    models.CharField(
                        blank=True,
                        help_text="e.g. single, double",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "lambda_max",
                    models.FloatField(
                        blank=True,
                        help_text="Wavelength of maximum absorbance",
                        null=True,
                    ),
                ),
                ("error", models.FloatField(blank=True, null=True)),
                (
                    "chromophore",
                    models.CharField(
                        blank=True, help_text="e.g. A1, A2", max_length=50, null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scp_assays",
                        to="core.reference",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeterologousData",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hetid", models.AutoField(primary_key=True, serialize=False)),
                ("mutations", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lambda_max",
                    models.FloatField(help_text="Wavelength of maximum absorbance"),
                ),
                ("error", models.FloatField(blank=True, null=True)),
                (
                    "cell_culture",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opsin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heterologous_records",
                        to="core.opsin",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heterologous_assays",
                        to="core.reference",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lambda_max__gte", 200), ("lambda_max__lte", 800)
                            ),
                            ("lambda_max", 0.0),
                            _connector="OR",
                        ),
                        name="valid_lambda_max_range",
                    )
                ],
            },
        ),
    ]
