# Generated by Django 5.2.8 on 2026-06-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasubmission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("PUBLICATION", "Publication Suggestion"),
                    ("DATA", "Direct Data Entry"),
                ],
                default="DATA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="heterologousdata",
            name="inference_source",
            field=models.CharField(
                blank=True, help_text="e.g. OPTICS, MNM", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="heterologousdata",
            name="is_inferred",
            field=models.BooleanField(
                default=False, help_text="Computationally inferred via MNM pipeline"
            ),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="data_type",
            field=models.CharField(
                blank=True, help_text="Heterologous or SCP", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="doi",
            field=models.CharField(
                default="No DOI",
                help_text="Required for Publication Suggestion",
                max_length=255,
            ),
        ),
    ]
