# Generated by Django 5.2.8 on 2026-03-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
