# Generated by Django 5.2.8 on 2026-03-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_reference_doi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heterologousdata",
            name="accession",
        ),
        migrations.RemoveField(
            model_name="heterologousdata",
            name="genus",
        ),
        migrations.RemoveField(
            model_name="heterologousdata",
            name="species",
        ),
        migrations.AddField(
            model_name="heterologousdata",
            name="opsin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="heterologous_records",
                to="core.opsin",
            ),
        ),
        migrations.AlterField(
            model_name="heterologousdata",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heterologous_assays",
                to="core.reference",
            ),
        ),
    ]
