# Generated by Django 5.2.8 on 2026-06-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_datasubmission_submission_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curatedscp",
            name="notes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
