# Generated by Django 5.2.8 on 2026-06-05 19:38

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

def delete_invalid_lambda_max_rows(apps, schema_editor):
    YourModel = apps.get_model("core", "CuratedSCP")

    invalid_qs = (
        YourModel.objects
        .filter(Q(lambda_max__lt=300) | Q(lambda_max__gt=800))
        .exclude(lambda_max=0)
    )

    invalid_qs.delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_curatedscp_source_dataset_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            delete_invalid_lambda_max_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="heterologousdata",
            name="valid_lambda_max_range",
        ),
        migrations.AddConstraint(
            model_name="curatedscp",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lambda_max__gte", 300), ("lambda_max__lte", 800)),
                    ("lambda_max", 0.0),
                    _connector="OR",
                ),
                name="valid_lambda_max_range_scp",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedscp",
            constraint=models.UniqueConstraint(
                fields=("genus", "species", "lambda_max"),
                name="unique_genus_species_lambda_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="heterologousdata",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lambda_max__gte", 300), ("lambda_max__lte", 800)),
                    ("lambda_max", 0.0),
                    _connector="OR",
                ),
                name="valid_lambda_max_range",
            ),
        ),
    ]
