# Generated by Django 5.2.8 on 2026-06-05 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_heterologousdata_valid_lambda_max_range_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="curatedscp",
            name="unique_genus_species_lambda_max",
        ),
        migrations.AddConstraint(
            model_name="curatedscp",
            constraint=models.UniqueConstraint(
                fields=("genus", "species", "lambda_max"),
                name="unique_genus_species_lambdamax",
            ),
        ),
    ]
