# Generated by Django 5.2.17 on 2026-09-09 10:50

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_curatedscp_unique_genus_species_lambda_max_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceMetadataAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=50)),
                ("original_value", models.JSONField(blank=True, null=True)),
                ("recovered_value", models.JSONField(blank=True, null=True)),
                ("provider", models.CharField(max_length=100)),
                ("evidence_url", models.TextField(blank=True)),
                ("retrieved_at", models.DateTimeField()),
                (
                    "decision",
                    models.CharField(
                        help_text="verified, candidate, conflict, classified, curator",
                        max_length=20,
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("run_id", models.CharField(max_length=100)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="VisualAcuity",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acuid", models.AutoField(primary_key=True, serialize=False)),
                ("genus", models.CharField(blank=True, max_length=100, null=True)),
                ("species", models.CharField(blank=True, max_length=100, null=True)),
                ("eye_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "body_length_cm",
                    models.FloatField(
                        blank=True,
                        help_text="BL (cm); source-specific body-length convention may be unknown",
                        null=True,
                        validators=[core.validators.positive_finite],
                    ),
                ),
                (
                    "interommatidial_angle_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Δϕ (degrees), angular separation of adjacent optical axes",
                        null=True,
                        validators=[core.validators.positive_finite],
                    ),
                ),
                (
                    "acceptance_angle_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Δρ (degrees), photoreceptor acceptance angle; source conventions may differ",
                        null=True,
                        validators=[core.validators.positive_finite],
                    ),
                ),
                (
                    "cpd",
                    models.FloatField(
                        blank=True,
                        help_text="Visual acuity in cycles per degree, preserved as supplied",
                        null=True,
                        validators=[core.validators.positive_finite],
                    ),
                ),
                (
                    "lens_diameter_mm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[core.validators.positive_finite],
                    ),
                ),
                (
                    "feller_ref_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "source_dataset",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_record_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All original columns, including raw taxonomic text",
                    ),
                ),
                (
                    "import_baseline",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Last imported normalized values for three-way updates",
                    ),
                ),
                ("quality_flags", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="curatedscp",
            name="unique_genus_species_lambdamax",
        ),
        migrations.AddField(
            model_name="reference",
            name="identifier_kind",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="measurement_methods",
            field=models.JSONField(
                blank=True,
                help_text="List of name, kind, uncertain, raw; source assertions, not bibliographic inference",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="mom_raw",
            field=models.TextField(
                blank=True,
                help_text="Original source MOM, including uncertainty",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="online_date",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[core.validators.partial_date],
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="print_date",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[core.validators.partial_date],
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="publication_date",
            field=models.CharField(
                blank=True,
                help_text="YYYY, YYYY-MM or YYYY-MM-DD; selected bibliographic date",
                max_length=10,
                null=True,
                validators=[core.validators.partial_date],
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="raw_citation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="source_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Original CSV columns; used to protect metadata on reimport",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referencemetadataaudit",
            name="reference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metadata_audits",
                to="core.reference",
            ),
        ),
        migrations.AddField(
            model_name="submissionreceipt",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.reference",
            ),
        ),
        migrations.AddField(
            model_name="visualacuity",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visualacuity",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acuity_observations",
                to="core.reference",
            ),
        ),
        migrations.AddField(
            model_name="visualacuity",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="visualacuity",
            constraint=models.UniqueConstraint(
                fields=("source_dataset", "source_record_id"),
                name="unique_acuity_source_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="visualacuity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_dataset__isnull", False),
                        models.Q(("source_dataset", ""), _negated=True),
                    ),
                    ("cpd__isnull", False),
                    _connector="OR",
                ),
                name="acuity_submission_requires_cpd",
            ),
        ),
        migrations.AddConstraint(
            model_name="visualacuity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("body_length_cm__isnull", True),
                    models.Q(
                        ("body_length_cm__gt", 0),
                        ("body_length_cm__lte", 1.7976931348623157e308),
                    ),
                    _connector="OR",
                ),
                name="acuity_valid_body_length_cm",
            ),
        ),
        migrations.AddConstraint(
            model_name="visualacuity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("interommatidial_angle_deg__isnull", True),
                    models.Q(
                        ("interommatidial_angle_deg__gt", 0),
                        ("interommatidial_angle_deg__lte", 1.7976931348623157e308),
                    ),
                    _connector="OR",
                ),
                name="acuity_valid_interommatidial_angle_deg",
            ),
        ),
        migrations.AddConstraint(
            model_name="visualacuity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("acceptance_angle_deg__isnull", True),
                    models.Q(
                        ("acceptance_angle_deg__gt", 0),
                        ("acceptance_angle_deg__lte", 1.7976931348623157e308),
                    ),
                    _connector="OR",
                ),
                name="acuity_valid_acceptance_angle_deg",
            ),
        ),
        migrations.AddConstraint(
            model_name="visualacuity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cpd__isnull", True),
                    models.Q(("cpd__gt", 0), ("cpd__lte", 1.7976931348623157e308)),
                    _connector="OR",
                ),
                name="acuity_valid_cpd",
            ),
        ),
        migrations.AddConstraint(
            model_name="visualacuity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lens_diameter_mm__isnull", True),
                    models.Q(
                        ("lens_diameter_mm__gt", 0),
                        ("lens_diameter_mm__lte", 1.7976931348623157e308),
                    ),
                    _connector="OR",
                ),
                name="acuity_valid_lens_diameter_mm",
            ),
        ),
    ]
