# Generated by Django 5.2.17 on 2026-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_private_submission_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=models.TextField(
                blank=True,
                help_text="DOI; legacy identifiers are retained until audited normalization",
                null=True,
            ),
        ),
    ]
