# Generated by Django 5.2.17 on 2026-09-09 13:22

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
import re
from urllib.parse import unquote, urlsplit


def retain_source_duplicates(apps, schema_editor):
    """Frozen, offline identity rules. Preserve every row, FK and approval field."""
    alias = schema_editor.connection.alias
    Reference = apps.get_model('core', 'Reference')
    SCP = apps.get_model('core', 'CuratedSCP')
    publications = {}
    for ref in Reference.objects.using(alias).all():
        doi = re.sub(r'^doi:\s*', '', (ref.doi or '').strip(), flags=re.I)
        if doi.startswith('10.'):
            doi = unquote(doi)
        try:
            url = urlsplit(doi)
            if url.hostname and url.hostname.lower() in {'doi.org', 'dx.doi.org'}:
                doi = unquote(url.path.lstrip('/'))
        except ValueError:
            pass
        publications[ref.pk] = ('doi', doi.lower()) if re.fullmatch(r'10\.\d{4,9}/[^\s"<>]+', doi, flags=re.I) else ('reference', ref.pk)
    groups = {}
    for row in SCP.objects.using(alias).filter(lambda_max__gt=0).order_by('pk'):
        key = ((row.genus or '').strip().lower(), (row.species or '').strip().lower(),
               row.lambda_max, publications.get(row.reference_id, ('missing', None)))
        groups.setdefault(key, []).append(row)
    rank = {'APPROVED': 0, 'PENDING': 1, 'REJECTED': 2}
    for rows in groups.values():
        rows.sort(key=lambda r: (rank[r.status], r.pk))
        if len(rows) > 1:
            SCP.objects.using(alias).filter(pk__in=[r.pk for r in rows[1:]]).update(duplicate_of_id=rows[0].pk)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_preserve_legacy_reference_identifiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="curatedscp",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Retained source duplicate; excluded from the public MSP/SCP table. No source data or approval history is deleted.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retained_duplicates",
                to="core.curatedscp",
            ),
        ),
        migrations.RunPython(retain_source_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="curatedscp",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim(
                        django.db.models.functions.comparison.Coalesce(
                            "genus", models.Value("")
                        )
                    )
                ),
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim(
                        django.db.models.functions.comparison.Coalesce(
                            "species", models.Value("")
                        )
                    )
                ),
                models.F("lambda_max"),
                django.db.models.functions.comparison.Coalesce(
                    "reference", models.Value(-1)
                ),
                condition=models.Q(
                    ("duplicate_of__isnull", True), ("lambda_max__gt", 0)
                ),
                name="unique_scp_taxon_wavelength_ref",
            ),
        ),
    ]
