# Generated by Django 5.2.17 on 2026-09-09 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_scp_reference_scoped_duplicates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("provider", models.CharField(max_length=20)),
                ("query_name", models.CharField(max_length=100)),
                ("completed_through", models.DateField(blank=True, null=True)),
                ("window_start", models.DateField(blank=True, null=True)),
                ("window_end", models.DateField(blank=True, null=True)),
                ("position", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveryRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="RUNNING", max_length=20)),
                ("config_hash", models.CharField(max_length=64)),
                ("configuration", models.JSONField(default=dict)),
                ("summary", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LiteratureCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("doi", models.TextField(blank=True)),
                ("source_url", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Provider metadata; verify against the paper before publishing.",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text="Search relevance only; these are NOT verified measurement methods.",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("DEFERRED", "Deferred"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=12,
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("NEEDS_DATA", "Needs data entry"),
                            ("COMPLETE", "Data entry complete"),
                            ("NOT_NEEDED", "No data entry needed"),
                        ],
                        default="NEEDS_DATA",
                        max_length=12,
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        help_text="Required when rejecting, deferring or reopening a rejected suggestion.",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.reference",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "literature inbox item",
                "verbose_name_plural": "literature inbox",
                "ordering": ["-first_seen"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryReviewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("note", models.TextField(blank=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_history",
                        to="core.literaturecandidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveryIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.TextField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identifiers",
                        to="core.literaturecandidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveryEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("provider_id", models.TextField()),
                ("query", models.TextField()),
                ("evidence_url", models.TextField()),
                ("retrieved_at", models.DateTimeField()),
                ("rationale", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.discoveryrun",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="core.literaturecandidate",
                    ),
                ),
            ],
        ),
    ]
