# Generated by Django 5.2.8 on 2026-10-07 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_literature_discovery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TuningAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(max_length=100)),
                ("object_type", models.CharField(max_length=30)),
                ("object_key", models.CharField(max_length=180)),
                ("before", models.JSONField(null=True)),
                ("after", models.JSONField()),
                ("reason", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TuningCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary experiment"),
                            ("REVIEW", "Review"),
                            ("CONTRADICTS", "Contradictory/no-effect evidence"),
                        ],
                        max_length=20,
                    ),
                ),
                ("locator", models.TextField(blank=True)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.reference"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TuningEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=180, unique=True)),
                ("title", models.CharField(max_length=250)),
                ("subtype", models.CharField(max_length=80)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("C_OPSIN", "Ciliary visual opsin"),
                            ("R_OPSIN", "Rhabdomeric visual opsin"),
                            ("OTHER", "Other / unsure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("organism", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEASURED", "Measured"),
                            ("LITERATURE", "Literature supported"),
                            ("PROPOSED", "Proposed candidate"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        help_text="List of {position, from, to}; null from/to means a site-level claim, not an established substitution."
                    ),
                ),
                ("original_notation", models.TextField(blank=True)),
                (
                    "baseline_label",
                    models.TextField(
                        blank=True,
                        help_text="Exact comparator construct, including background mutations/chimerism",
                    ),
                ),
                ("baseline_nm", models.FloatField(blank=True, null=True)),
                ("mutant_nm", models.FloatField(blank=True, null=True)),
                (
                    "reported_shift_nm",
                    models.FloatField(
                        blank=True,
                        help_text="Only an explicitly published signed shift; never a predicted target effect",
                        null=True,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "source_locator",
                    models.TextField(
                        help_text="Figure/table/page or source row identifying this assertion"
                    ),
                ),
                ("release", models.CharField(max_length=60)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mutant_assay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tuning_mutants",
                        to="core.heterologousdata",
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        through="core.TuningCitation", to="core.reference"
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wild_type_assay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tuning_comparators",
                        to="core.heterologousdata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tuningcitation",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="core.tuningevidence",
            ),
        ),
        migrations.CreateModel(
            name="TuningProtein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("C_OPSIN", "Ciliary visual opsin"),
                            ("R_OPSIN", "Rhabdomeric visual opsin"),
                            ("OTHER", "Other / unsure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subtype", models.CharField(blank=True, max_length=50)),
                ("accession", models.CharField(blank=True, max_length=100)),
                ("sequence", models.TextField()),
                ("numbering_note", models.TextField()),
                ("provenance", models.JSONField(default=dict)),
                (
                    "structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pinned structure ID/file, chain and sequence-to-coordinate map",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tuningevidence",
            name="protein",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tuning_evidence",
                to="core.tuningprotein",
            ),
        ),
        migrations.AddConstraint(
            model_name="tuningcitation",
            constraint=models.UniqueConstraint(
                fields=("evidence", "reference", "role"), name="unique_tuning_citation"
            ),
        ),
    ]
