# Generated by Django 5.2.8 on 2026-10-07 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_tuning_mapper"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TuningCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("analysis", models.JSONField(default=dict)),
                ("outcome", models.CharField(db_index=True, max_length=50)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Published)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "selection",
                    models.CharField(
                        blank=True,
                        help_text="A supported comparator/numbering option from the analysis.",
                        max_length=100,
                    ),
                ),
                (
                    "numbering_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="I checked the publication’s numbering against the source protein.",
                    ),
                ),
                (
                    "conditions_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="I checked that comparator and mutant use compatible constructs, chromophore, pH and measurement conditions.",
                    ),
                ),
                (
                    "cross_publication_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="For a WT from another publication: I checked both sources and justified this cross-study comparison in the review note.",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        help_text="Cite the publication figure/table/page and explain the confirmed numbering and comparator.",
                    ),
                ),
                ("reviewed_fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "stale",
                    models.BooleanField(
                        default=False,
                        help_text="Source inputs changed after extraction/review; re-extract and review before publication.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tuning_candidate",
                        to="core.heterologousdata",
                    ),
                ),
                (
                    "evidence",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extracted_candidate",
                        to="core.tuningevidence",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
