# Generated by Django 5.2.8 on 2026-10-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_tuning_single_site_candidates"),
    ]

    operations = [
        migrations.AddField(
            model_name="heterologousdata",
            name="mutation_build",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="WT-derived construct provenance and audited source corrections; never a predicted wavelength.",
            ),
        ),
        migrations.AddField(
            model_name="heterologousdata",
            name="mutation_numbering",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bovine", "Bovine"),
                    ("human", "Human (human opsins only)"),
                    ("squid", "Squid"),
                    ("self", "WT sequence"),
                    ("spider", "Spider"),
                ],
                help_text="Leave blank for bovine → human → squid → self → spider; set when the publication explicitly specifies numbering.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tuningcandidate",
            name="approval_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTO", "Automatic sequence match"),
                    ("MANUAL", "Curator approval"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tuningcandidate",
            name="approval_policy",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tuningcandidate",
            name="require_condition_match",
            field=models.BooleanField(
                default=False,
                help_text="Optional: require matching, nonblank cell culture, purification and spectrum labels before approval.",
            ),
        ),
    ]
