# Generated by Django 5.2.8 on 2026-10-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_wt_mutant_import_and_auto_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="heterologousdata",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Retained measurement. Archived duplicates are excluded from public data and tuning extraction.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archived_duplicates",
                to="core.heterologousdata",
            ),
        ),
    ]
