# Generated by Django 5.2.8 on 2026-10-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_heterologous_archived_duplicates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opsin",
            name="accession",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="tuningprotein",
            name="accession",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
