"""Grouped-site browser checks. Use only an isolated localhost VPOD server."""
import argparse,csv,io,json
from pathlib import Path
from playwright.sync_api import sync_playwright
parser=argparse.ArgumentParser();parser.add_argument('--url',default='http://127.0.0.1:8774');parser.add_argument('--output',default='/tmp/vpod-site-browser');args=parser.parse_args()
out=Path(args.output);out.mkdir(parents=True,exist_ok=True)
report={'checks':[],'errors':[]}
def check(name,condition):
    assert condition,name
    report['checks'].append(name);print('PASS',name,flush=True)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
    page=browser.new_page(viewport={'width':1400,'height':1000});page.on('pageerror',lambda e:report['errors'].append(str(e)))
    page.goto(args.url,wait_until='domcontentloaded');page.locator('#tab-tuning').click();page.wait_for_function('VpodTuning.state.initialized')
    check('Site catalogue visible by default',page.locator('.tm-site-group').count()>1)
    page.locator('#tmSearch').fill('83')
    check('Numeric search matches displayed site only',page.locator('.tm-site-group').count()>0 and page.locator('.tm-site-group').evaluate_all('(nodes)=>nodes.every(n=>n.dataset.siteKey.endsWith("|83"))'))
    page.locator('#tmSearch').fill('99999')
    check('Unknown site shows an empty catalogue',page.locator('.tm-site-group').count()==0 and page.locator('#tmCatalogueEmpty').is_visible())
    page.locator('#tmSearch').fill('')
    key='bovine|C_OPSIN|bovine|83';group=page.locator(f'[data-site-key="{key}"]')
    check('Site 83 collects multiple study assertions',group.locator('[data-key]').count()>1)
    toggle=group.locator('.tm-site-toggle');toggle.focus();page.keyboard.press('Enter')
    check('Site opens from keyboard',toggle.get_attribute('aria-expanded')=='true')
    variant=group.locator('input[data-variant]').first
    variant.check();check('Mutation group selects its study evidence',page.evaluate('VpodTuning.state.selected.size')>0)
    controls=variant.locator('xpath=ancestor::div[@class="tm-mutation-group"]');controls.locator('button').click()
    first=controls.locator('[data-key]').first
    if controls.locator('[data-key]').count()>1:
        first.uncheck();check('Partial mutation selection is shown',variant.evaluate('(n)=>n.indeterminate'))
    page.screenshot(path=str(out/'site-groups-desktop.png'),full_page=True)
    page.locator('#tmClear').click();group.locator('input[data-site]').check();page.locator('#tmExample').click();page.locator('#tmMap').click();page.wait_for_function('VpodTuning.state.result!==null',timeout=45000)
    result=page.evaluate('VpodTuning.state.result')
    check('Site-only selection maps one row',len(result['rows'])==1 and result['rows'][0]['selection_kind']=='SITE')
    check('Site-only selection prescribes no mutation or shift',result['rows'][0]['source_to'] is None and result['rows'][0]['shift_nm_in_source'] is None)
    check('Site-only mapping retains supporting studies',len(result['evidence'])>1)
    with page.expect_download() as download:page.locator('#tmExport').click()
    download.value.save_as(out/'site-only.csv');rows=list(csv.DictReader(io.StringIO((out/'site-only.csv').read_text())))
    check('Site CSV preserves selection type and references',rows[0]['selection_kind']=='SITE' and rows[0]['source_dois'] not in ('','[]') and rows[0]['mutation_status']=='SITE_ONLY')
    with page.expect_download() as download:page.locator('#tmSessionExport').click()
    download.value.save_as(out/'site-session.json')
    page.locator('#tmClear').click();page.locator('#tmSessionFile').evaluate('(n)=>n.closest("details").open=true');page.set_input_files('#tmSessionFile',str(out/'site-session.json'))
    page.wait_for_function('VpodTuning.state.selectedSites.size===1')
    check('Site-only session restores selection, not saved result',page.evaluate('VpodTuning.state.result===null'))
    page.select_option('#tmReference','human-lws')
    check('Reference change clears old site-only coordinates',page.evaluate('VpodTuning.state.selectedSites.size===0'))
    check('Catalogue labels use selected reference numbering','Human' in page.locator('#tmGroupingNote').inner_text())
    page.select_option('#tmFamily','R_OPSIN');page.locator('#tmSearch').fill('spider-e181d')
    check('Search retains only matching site groups',page.locator('.tm-site-group').count()==1)
    choice=page.locator('[data-key="spider-e181d"]').first;card=choice.locator('xpath=ancestor::article');card.locator('.tm-site-toggle').click()
    mutation=choice.locator('xpath=ancestor::div[@class="tm-mutation-group"]');mutation.locator('input[data-variant]').check()
    seq=page.evaluate('VpodTuning.state.templates.find(p=>p.key==="spider").sequence')
    targets='\n'.join('>'+name+'\n'+seq[:193]+aa+seq[194:] for name,aa in [('matching','E'),('different','A'),('already','D'),('unknown','X')])
    page.locator('#tmFasta').fill(targets);page.locator('#tmMap').click();page.wait_for_function('VpodTuning.state.result!==null',timeout=45000)
    result=page.evaluate('VpodTuning.state.result');statuses={r['target_name']:r['mutation_status'] for r in result['rows']}
    check('Each sequence has its own compatibility assessment',statuses=={'matching':'START_MATCHES','different':'RESIDUE_MISMATCH','already':'ALREADY_PRESENT','unknown':'UNCERTAIN'})
    text=page.locator('#tmMappingRows').inner_text();check('Mismatch and already-present warnings are visible','Different starting residue' in text and 'Replacement already present' in text)
    check('Only matching residue receives a target mutation notation',[(r['target_name'],r['target_mutation']) for r in result['rows'] if r['target_mutation']]==[('matching','E194D')])
    with page.expect_download() as download:page.locator('#tmExport').click()
    download.value.save_as(out/'mutations.csv');rows=list(csv.DictReader(io.StringIO((out/'mutations.csv').read_text())))
    check('Mutation compatibility is preserved in CSV',{r['target_name']:r['mutation_status'] for r in rows}==statuses)
    page.set_viewport_size({'width':390,'height':844});page.screenshot(path=str(out/'site-groups-mobile.png'),full_page=True)
    check('No horizontal page overflow on mobile',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
    page.locator('#tmClear').click();page.locator('#tmSearch').fill('spider-e181d');page.locator('input[data-site]').check();page.locator('#tmOpenStructures').click()
    page.select_option('#tmStructureReference','spider');page.locator('#tmLoadReference').click();page.wait_for_function('VpodStructures.slots.Reference?.file?.name.includes("6I9K")',timeout=60000)
    page.locator('#tmReferenceMark').click();page.wait_for_function('VpodStructures.slots.Reference.mappings.length>0',timeout=45000)
    check('Site-only selection also marks structure residue',page.evaluate('VpodStructures.slots.Reference.mappings[0].author_residue')==194)
    check('No browser exceptions',not report['errors']);browser.close()
(out/'report.json').write_text(json.dumps(report,indent=2));print('Report:',out/'report.json')
